categories:
    - 'kfokofe'
    - 'feokfeokfo'

tricks:
    Chicken Salad:
        category: 'kfokofe'
        description: 'ofekfeolkpkokolkkoojojojk'
        images:
            - '33.jpeg'
            - '34.jpeg'
        videos:
            - '<iframe width="560" height="315" src="https:fkofekU" frameborder="0" allowfullscreen></iframe>'
            - '<iframe width="560" height="315" src="https:fkofekU" frameborder="0" allowfullscreen></iframe>'
    Seatbelt:
        category: 'feokfeokfo'
        description: 'Une description de la figure...'
        images:
            - '35.jpeg'
        videos:
            - '<iframe width="560" height="315" src="https:fkofekU" frameborder="0" allowfullscreen></iframe>'
            - '<iframe width="560" height="315" src="https:fkofekU" frameborder="0" allowfullscreen></iframe>'
