services:
#    snow_tricks.example:
#        class: SnowTricksBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    SnowTricksBundle\Doctrine\ImageManagementListener:
        arguments:
            $imageDir: "%trick.server.image_directory%"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }
